version: '3.8'

services:
  api:
    build: .
    container_name: api_usuarios
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: